-- SCRIPT: Creación de Esquema
-- Sistema de Gestión de Restaurante

DROP TABLE DETALLE_PEDIDO CASCADE CONSTRAINTS;
DROP TABLE PEDIDO CASCADE CONSTRAINTS;
DROP TABLE PLATO CASCADE CONSTRAINTS;
DROP TABLE MESA CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;