CREATE TABLE CLIENTE (
  COD_CLIENTE NUMBER(4) PRIMARY KEY,
  NOMBRE VARCHAR2(30),
  TELEFONO NUMBER(9)
);

CREATE TABLE PLATO (
  COD_PLATO VARCHAR2(5) PRIMARY KEY,
  NOMBRE VARCHAR2(30),
  PRECIO NUMBER(6,2)
);

CREATE TABLE MESA (
  COD_MESA NUMBER(3) PRIMARY KEY,
  NUMERO_MESA NUMBER(3),
  CAPACIDAD NUMBER(2),
  ESTADO VARCHAR2(15)
);

CREATE TABLE PEDIDO (
  COD_PEDIDO NUMBER(5) PRIMARY KEY,
  FECHA_PEDIDO DATE,
  COD_CLIENTE NUMBER(4),
  COD_MESA NUMBER(3),
  CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE),
  CONSTRAINT FK_PEDIDO_MESA FOREIGN KEY (COD_MESA) REFERENCES MESA(COD_MESA)
);

CREATE TABLE DETALLE_PEDIDO (
  COD_PEDIDO NUMBER(5),
  COD_PLATO VARCHAR2(5),
  CANTIDAD NUMBER(3),
  PRIMARY KEY (COD_PEDIDO, COD_PLATO),
  CONSTRAINT FK_DETALLE_PEDIDO_PEDIDO FOREIGN KEY (COD_PEDIDO) REFERENCES PEDIDO(COD_PEDIDO),
  CONSTRAINT FK_DETALLE_PEDIDO_PLATO FOREIGN KEY (COD_PLATO) REFERENCES PLATO(COD_PLATO)
);

-- MODIFICACIONES A TABLAS
ALTER TABLE CLIENTE
ADD CONSTRAINT CHK_TELEFONO CHECK (TELEFONO >= 900000000 AND TELEFONO <= 999999999);

ALTER TABLE PLATO
ADD CONSTRAINT CHK_PRECIO CHECK (PRECIO > 0);

ALTER TABLE MESA
ADD CONSTRAINT CHK_CAPACIDAD CHECK (CAPACIDAD > 0);

ALTER TABLE MESA
MODIFY NUMERO_MESA UNIQUE;

-- ÍNDICES
CREATE INDEX IDX_PEDIDO_CLIENTE ON PEDIDO(COD_CLIENTE);
CREATE INDEX IDX_PEDIDO_MESA ON PEDIDO(COD_MESA);
CREATE INDEX IDX_DETALLE_PLATO ON DETALLE_PEDIDO(COD_PLATO);